# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fa
  pod 'AFNetworking', '~> 3.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'GoogleMaps'
  pod 'DSBarChart', '~> 0.4.0'
end
